# Generated by Django 2.1.2 on 2018-11-09 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='created',
        ),
        migrations.AddField(
            model_name='state',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='backend.Country'),
        ),
    ]
